# Generated by Django 6.0.2 on 2026-03-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='lable',
            new_name='label',
        ),
    ]
