# Generated by Django 6.0.2 on 2026-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_address_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(default='00-000', max_length=6),
        ),
    ]
