# Generated by Django 6.0.2 on 2026-03-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_Correction_type_Tag_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
